### ISSUE TITLE
Jovi in Car必备好用APP

### ISSUE THREAD

**Issue by qwertzhuce** [brilliantfeat/AutoNaviIncar#1]
感谢作者提供，顺便请教下，除了修改包名，破解启动验证，还需要修改其他地方么？谢谢

**Comment by brilliantfeat** [comment]
> 感谢作者提供，顺便请教下，除了修改包名，破解启动验证，还需要修改其他地方么？谢谢

已将修改部分源码上传，请自行查看

**Comment by brilliantfeat** [comment]
issue

**Comment by qwertzhuce** [comment]
> > 感谢作者提供，顺便请教下，除了修改包名，破解启动验证，还需要修改其他地方么？谢谢
> 
> 已将修改部分源码上传，请自行查看

再次向作者表示感谢 

> > 感谢作者提供，顺便请教下，除了修改包名，破解启动验证，还需要修改其他地方么？谢谢
> 
> 已将修改部分源码上传，请自行查看

谢谢

**Comment by yaowangyw** [comment]
可以的，先发个灰度我们用户先测测
