### ISSUE TITLE
作者您好，这是高德的auto SDK吗

### ISSUE THREAD

**Issue by ljphawk** [brilliantfeat/AutoNaviIncar#10]
作者您好，这是高德的auto SDK吗？
是收费的吗

**Comment by brilliantfeat** [comment]
> 作者您好，这是高德的auto SDK吗？
> 是收费的吗

调用广播协议API，以前可在官网公开浏览，现在好像仅为车企商业合作提供

**Comment by ljphawk** [comment]
> > 作者您好，这是高德的auto SDK吗？
> > 是收费的吗
> 
> 调用广播协议API，以前可在官网公开浏览，现在好像仅为车企商业合作提供

怪不得没找到相关文档，谢谢解惑
