### ISSUE TITLE
高德地图车机版已经发布Auto_6.2.0.600914_alpha可否跟进？谢谢！

### ISSUE THREAD

**Issue by GuoKai1203** [brilliantfeat/AutoNaviIncar#13]
高德地图车机版已经发布Auto_6.2.0.600914_alpha可否跟进？谢谢！
https://lbsbbs.amap.com/forum.php?mod=viewthread&tid=66765&extra=page%3D1

http://mapdownload.autonavi.com/apps/auto/manual/V620/Auto_6.2.0.600914_alpha.apk

**Comment by brilliantfeat** [comment]
好

**Comment by brilliantfeat** [comment]
> 高德地图车机版已经发布Auto_6.2.0.600914_alpha可否跟进？谢谢！
> https://lbsbbs.amap.com/forum.php?mod=viewthread&tid=66765&extra=page%3D1
> 
> 
> http://mapdownload.autonavi.com/apps/auto/manual/V620/Auto_6.2.0.600914_alpha.apk

已更新，未经测试，请自测。

**Comment by GuoKai1203** [comment]
谢谢！已经用上了，功能都正常～
