### ISSUE TITLE
发现一个问题，不知是什么情况。

### ISSUE THREAD

**Issue by GuoKai1203** [brilliantfeat/AutoNaviIncar#14]
使用该修改版，导航无法累计到行程里面。没有对应的导航记录

**Comment by brilliantfeat** [comment]
> 使用该修改版，导航无法累计到行程里面。没有对应的导航记录

是登录的同一账号吗？我的可以同步的

**Comment by Jlrom** [comment]
是登陆的同一个账号，车机端的同步停止在了6月23号，但是手机端的正常，但是实际导航用的是车机端的导航

**Comment by GuoKai1203** [comment]
> > 使用该修改版，导航无法累计到行程里面。没有对应的导航记录
> 
> 是登录的同一账号吗？我的可以同步的

是同一账号登陆的，不知道什么原因，手机端能正常显示导航的数据，车机端不行了，数据停留在了6月23号，我回头清除数据看看！

**Comment by brilliantfeat** [comment]
> > > 使用该修改版，导航无法累计到行程里面。没有对应的导航记录
> > 
> > 是登录的同一账号吗？我的可以同步的
> 
> 是同一账号登陆的，不知道什么原因，手机端能正常显示导航的数据，车机端不行了，数据停留在了6月23号，我回头清除数据看看！

没有问题![IMG_20220701_162353.jpg](https://user-images.githubusercontent.com/31770465/176856005-fc2a8f22-ef57-446d-8ae7-40591506d5cc.jpg)

**Comment by GuoKai1203** [comment]
> > > > 使用该修改版，导航无法累计到行程里面。没有对应的导航记录
> > > 
> > > 
> > > 是登录的同一账号吗？我的可以同步的
> > 
> > 
> > 是同一账号登陆的，不知道什么原因，手机端能正常显示导航的数据，车机端不行了，数据停留在了6月23号，我回头清除数据看看！
> 
> 没有问题![IMG_20220701_162353.jpg](https://user-images.githubusercontent.com/31770465/176856005-fc2a8f22-ef57-446d-8ae7-40591506d5cc.jpg)

手机端确实是会显示到最新的，车机端那个不会显示最新的，不知道什么原因，可能我在多个设备上同时登陆了一个账号吧

**Comment by GuoKai1203** [comment]
> > > > 使用该修改版，导航无法累计到行程里面。没有对应的导航记录
> > > 
> > > 
> > > 是登录的同一账号吗？我的可以同步的
> > 
> > 
> > 是同一账号登陆的，不知道什么原因，手机端能正常显示导航的数据，车机端不行了，数据停留在了6月23号，我回头清除数据看看！
> 
> 没有问题![IMG_20220701_162353.jpg](https://user-images.githubusercontent.com/31770465/176856005-fc2a8f22-ef57-446d-8ae7-40591506d5cc.jpg)

确实比较奇怪，我回头把其他设备上的账号退出看看

![微信图片_20220701163920](https://user-images.githubusercontent.com/3240707/176858513-09c82715-ea71-4046-8299-eb8629a70c09.jpg)
![微信图片_20220701163930](https://user-images.githubusercontent.com/3240707/176858561-63675526-e802-48d3-af15-474e1274bd0d.jpg)
