### ISSUE TITLE
AUTO V6.2.0 内测版更新啦！(7月15日更新）

### ISSUE THREAD

**Issue by GuoKai1203** [brilliantfeat/AutoNaviIncar#16]
https://mapdownload.autonavi.com/apps/auto/manual/V620/Auto_6.2.0.601048_alpha.apk

主要修复了稳定性问题和导航结束页里程为零问题和平均车速异常问题。

这个版本解决了 里程同步的问题，希望更新，谢谢！

很抱歉来催更，因为我用您开源的代码修改出来的无法正常使用，希望理解，谢谢！
![1](https://user-images.githubusercontent.com/3240707/179222607-4b70d4c5-4ddf-4387-857a-7ac573add8dc.png)

**Comment by GuoKai1203** [comment]
目前上面那个弹窗已经解决了，但是模拟器可以正常安装正常打开，到手机上就提示解析包错误了，技术太菜，希望大佬指点！

**Comment by brilliantfeat** [comment]
有签名认证，你修改需要去掉签名认证。

**Comment by brilliantfeat** [comment]
晚上有空的时候更新一下吧

**Comment by brilliantfeat** [comment]
> 目前上面那个弹窗已经解决了，但是模拟器可以正常安装正常打开，到手机上就提示解析包错误了，技术太菜，希望大佬指点！

弹窗是签名验证，模拟器能安装，手机解析错误说明旧系统可以用，新系统用不了，是API版本不对应或者新API的验证错误，请查阅安卓API相关文件

**Comment by GuoKai1203** [comment]
> 晚上有空的时候更新一下吧

非常感谢，我改天再研究看看！

**Comment by brilliantfeat** [comment]
已更新，请自测

**Comment by GuoKai1203** [comment]
> 已更新，请自测
已测，感谢大佬，正在研究中~
