### ISSUE TITLE
高德车机版已发布6.2正式版，大佬是否能更新下

### ISSUE THREAD

**Issue by taanng** [brilliantfeat/AutoNaviIncar#17]
高德地图车机版V6.2.0正式版
https://mapdownload.autonavi.com/apps/auto/manual/V620/Auto_V6.2.0.601346_release_signed.apk?u=079b69804842ce8440dbb582ed990613&

**Comment by brilliantfeat** [comment]
好的，等下看下。

**Comment by taanng** [comment]
.

**Comment by taanng** [comment]
.
