### ISSUE TITLE
1、怎么关巡航呀。2、高德的行程记录不会和手机那样有急加速、急刹和超速这些，永远是100分…

### ISSUE THREAD

**Issue by Rampage04** [brilliantfeat/AutoNaviIncar#21]
1、怎么关巡航呀。2、高德的行程记录不会和手机那样有急加速、急刹和超速这些，永远是100分…

**Comment by liuzy1128** [comment]
不想用巡航就用手机版啊 用车机版不就是看中巡航模式了吗

**Comment by Rampage04** [comment]
> 不想用巡航就用手机版啊 用车机版不就是看中巡航模式了吗
很久之前换用车机版的，好像手机版选路线没用，选完了车机上还是默认的

**Comment by brilliantfeat** [comment]
关闭巡航：设置-播报_自动巡航播报，同步问题请向官方反馈
