### ISSUE TITLE
首页小窗巡航状态下导航信息小卡片显示bug

### ISSUE THREAD

**Issue by qwertzhuce** [brilliantfeat/AutoNaviIncar#3]
![mmexport1648774994734](https://user-images.githubusercontent.com/48362363/161174752-42be083f-0058-47c7-83ef-82e412bfdd24.jpg)
车友测试 小窗巡航直行状态下 也会显示拐弯提示 不知道作者有没有遇到这个情况呢？再次对作者的辛苦付出表示感谢

**Comment by brilliantfeat** [comment]
好的，我看看

**Comment by yaowangyw** [comment]
> 好的，我看看

是的，我的车机也是这个问题，巡航状态下，应该把右侧的导航小卡标去掉

**Comment by brilliantfeat** [comment]
确实这样，等下修改下

**Comment by brilliantfeat** [comment]
> ![mmexport1648774994734](https://user-images.githubusercontent.com/48362363/161174752-42be083f-0058-47c7-83ef-82e412bfdd24.jpg) 车友测试 小窗巡航直行状态下 也会显示拐弯提示 不知道作者有没有遇到这个情况呢？再次对作者的辛苦付出表示感谢

确实这样，等下修改下

**Comment by qwertzhuce** [comment]
> 确实这样，等下修改下

万分感谢

**Comment by cmf866** [comment]
大神，辛苦了 有你们这样的大神真好

**Comment by brilliantfeat** [comment]
> ![mmexport1648774994734](https://user-images.githubusercontent.com/48362363/161174752-42be083f-0058-47c7-83ef-82e412bfdd24.jpg) 车友测试 小窗巡航直行状态下 也会显示拐弯提示 不知道作者有没有遇到这个情况呢？再次对作者的辛苦付出表示感谢

已修复该问题并上传release，如需要可前去下载。
