### ISSUE TITLE
hicar 有没有办法破？

### ISSUE THREAD

**Issue by knifecutter** [brilliantfeat/AutoNaviIncar#5]

**Comment by brilliantfeat** [comment]
我没有华为手机，车机也只支持carlife和carplay，可以去尝试下载hicar sdk看看，我没关注过hicar，按照协议修改apk应该问题不大的。

**Comment by qwertzhuce** [comment]
> 我没有华为手机，车机也只支持carlife和carplay，可以去尝试下载hicar sdk看看，我没关注过hicar，按照协议修改apk应该问题不大的。

通用的汽车？
