### ISSUE TITLE
4.13的高德车机版小窗巡航模式下时速表不显示，还有几个版本都存在全屏和窗切换过程中画面会出现重叠，搜索框会一直卡在大图界面，只有重启应用才能解决，希望可以解决下。

### ISSUE THREAD

**Issue by Endlesslongh** [brilliantfeat/AutoNaviIncar#6]

**Comment by qwertzhuce** [comment]
4.13还没尝鲜，重叠情况好像从来没有出现过

**Comment by brilliantfeat** [comment]
好的，巡航状态UI层会在下一版本加入，画面出现错乱这个问题可能是在切换时正好是surfaceview更新画面的时候导致，因为没有向其他应用一样在小窗单独有一个activity，surfaceview画面更新都会在上一画面基础上更新画面，所以问题比较难解决，有空的时候好好看看。

**Comment by brilliantfeat** [comment]
看了下这个可能和手机性能有关，可能是锁屏之后降频了导致，可以在开发者模式打开充电不锁屏选项
