### ISSUE TITLE
小窗导航时，整体布局没有居中，右侧被切掉一部分

### ISSUE THREAD

**Issue by cxyao** [brilliantfeat/AutoNaviIncar#8]
丰田亚洲龙，小窗导航时，整体布局没有居中，右侧被切掉一部分。望大神能抽空对应一下。
![微信图片_20220422085520](https://user-images.githubusercontent.com/4005099/164576149-7849a733-9387-46e3-841f-e16e1696ba6a.jpg)

**Comment by brilliantfeat** [comment]
这个问题如果存在用其他地图也会有，是incar系统分配的虚拟屏幕问题，我没有高德地图车机版的源码，是修改不了的哦
